project:
  type: default
  output-dir: docs

website:
  title: "Olympic Games Dashboard"
  navbar:
    left:
      - text: "Olympics Dashboard"
        href: index.html  # Cambié la ruta al archivo index.html

output-dir: docs

format:
  dashboard:
    orientation: columns
    nav-buttons: [github]
    github: https://github.com/Prosasmed/usaer_dashboard2.git
    theme: cosmo  # Cambia 'sketchy' por 'cosmo' o 'simple'
    logo: images/logo2.png

resources:
  - style/**   # Incluir todos los archivos dentro de la carpeta style
  - images/**  # Incluir todos los archivos dentro de la carpeta images



