project:
  type: default
  output-dir: docs

website:
  title: "Olympic Games Dashboard"
  navbar:
    left:
      - text: "Olympics Dashboard"
        href: olympicdash-r-1.qmd

output-dir: docs

format:
  dashboard:
    orientation: columns
    nav-buttons: [github]
    github: https://github.com/Prosasmed/usaer_dashboard2.git
    theme:
      - sketchy
      - style/olympicdash.scss
    logo: images/logo2.png

resources:
  - style/**   # Incluir todos los archivos dentro de la carpeta style
  - images/**  # Incluir todos los archivos dentro de la carpeta images


